config/routes.rb
Rails.application.routes.draw do
  resources :shopping_carts
  resources :reviews
  resources :consumers
  resources :farmers
	resources :produces
  resources :after_signup
  resources :users, only: [:edit, :update]
  devise_for :users, controllers: { 
  	registrations: 'registrations', 
  	confirmations: 'confirmations'
  }

  resources :line_items do 
    member do 
      patch 'increase_quan'
      patch 'decrease_quan'
    end
  end

  resources :orders do 
    member do
      patch "accept"
      patch "mark_as_complete"
      patch "cancel"
    end
  end

  get 'dashboard/index'
  get 'home/landing'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consumer.rb
class Consumer < ApplicationRecord
  belongs_to :user
	has_many :reviews
  has_one :shoppingcart

  def self.find_by_current_user(current_user_id)
  	self.find_by_user_id(current_user_id)
  end
end

app/models/farm.rb
class Farm < ApplicationRecord
  belongs_to :user
  has_many :produce

	mount_uploader :image, ImageUploader
	
	validates :name, presence: true, uniqueness: true
	validates :description, presence: true
	validates :address_line_1, presence: true
	validates :address_line_2, presence: true
end

app/models/farmer.rb
class Farmer < ApplicationRecord
  belongs_to :user
  has_many :produces
  has_many :reviews

  validates :farm_name, presence: true, uniqueness: true

  def has_consumer_review(id)
    reviews.where(consumer_id: id).present?
  end

  def review
  	reviews.present? ? "#{reviews.average(:rating).ceil} Stars" : "0 Stars"
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :shopping_cart
  belongs_to :order, optional: true
  
  validates :quantity, numericality: { greater_than_or_equal_to: 1 }
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :line_items
	enum status: [:pending, :accepted, :fulfilled, :cancelled]

	def change_status(status)
		update_attributes(status: status)
	end

	def assign_badge_class
		if pending?
			"badge-warning text-white"
		elsif accepted?
			"badge-primary"
		elsif fulfilled?
			"badge-success"
		else
			"badge-danger"
		end	
	end
end

app/models/produce.rb
class Produce < ApplicationRecord
  belongs_to :farmer

	mount_uploaders :images, ImageUploader

  validates :name, presence: true
  validates :description, presence: true

  def seller
  	Farmer.find_by_id(farmer_id)
  end

  def available_to_string
    available? ? "Yes" : "No"  
  end

  def available_badge_class
    available? ? "badge-success" : "badge-danger"  
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :consumer
	belongs_to :farmer, optional: true

	validates :rating, presence: true
	validates :comment, presence: true
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
	has_many :line_items, dependent: :destroy
  belongs_to :consumer

  def self.user_cart(user)
  	self.find_by_consumer_id(Consumer.find_by_user_id(user.id))
  end

  def amound_in_cart
  	line_items.where(order_id: nil).count
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :farmers
	has_many :consumers
  enum state: [:active, :deactivated]

  # validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :address_line_1, presence: true
  # validates :city, presence: true
  # validates :parish, presence: true
  # validates :phone_number, length: { is: 7 }, numericality: { only_integer: true }

  accepts_nested_attributes_for :farmers

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, 
         :timeoutable, :timeout_in => 20.minutes

	mount_uploader :avatar, ImageUploader

 	def consumer?
 		account_type == "consumer"
 	end

 	def farmer?
 		account_type == "farmer"
 	end

end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_action :set_shopping_cart, only: [:show, :edit, :update, :destroy]

  # GET /shopping_carts
  # GET /shopping_carts.json
  def index
    @shopping_carts = ShoppingCart.all
  end

  # GET /shopping_carts/1
  # GET /shopping_carts/1.json
  def show
    @line_items = @shopping_cart.line_items.where(order_id: nil).order('produce_id')
    @recommendations = Order.where(status: 2).where("created_at >= ?", 5.days.ago.utc).map { |order|  order.line_items.first  }
  end

  # GET /shopping_carts/new
  def new
    @shopping_cart = ShoppingCart.new
  end

  # GET /shopping_carts/1/edit
  def edit
  end

  # POST /shopping_carts
  # POST /shopping_carts.json
  def create
    @shopping_cart = ShoppingCart.new(shopping_cart_params)

    respond_to do |format|
      if @shopping_cart.save
        format.html { redirect_to @shopping_cart, notice: 'Shopping cart was successfully created.' }
        format.json { render :show, status: :created, location: @shopping_cart }
      else
        format.html { render :new }
        format.json { render json: @shopping_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shopping_carts/1
  # PATCH/PUT /shopping_carts/1.json
  def update
    respond_to do |format|
      if @shopping_cart.update(shopping_cart_params)
        format.html { redirect_to @shopping_cart, notice: 'Shopping cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @shopping_cart }
      else
        format.html { render :edit }
        format.json { render json: @shopping_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopping_carts/1
  # DELETE /shopping_carts/1.json
  def destroy
    @shopping_cart.destroy
    respond_to do |format|
      format.html { redirect_to shopping_carts_url, notice: 'Shopping cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping_cart
      @shopping_cart = ShoppingCart.find_by_consumer_id(Consumer.find_by_user_id(current_user.id))

    end

    # Only allow a list of trusted parameters through.
    def shopping_cart_params
      params.require(:shopping_cart).permit(:consumer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def toastr_flash
	  flash.each_with_object([]) do |(type, message), flash_messages|
	    type = 'success' if type == 'notice'
	    type = 'error' if type == 'alert'
	    text = "<script>toastr.#{type}('#{message}', '', { closeButton: true, progressBar: true })</script>"
	    flash_messages << text.html_safe if message
	  end.join("\n").html_safe
	end
end

app/helpers/consumers_helper.rb
module ConsumersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper

end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/produces_helper.rb
module ProducesHelper

	def set_image(produce)
		produce.images.present? ? produce.images.first.url : "data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22348%22%20height%3D%22225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20348%20225%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1761819ef79%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A17pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1761819ef79%22%3E%3Crect%20width%3D%22348%22%20height%3D%22225%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22116.2265625%22%20y%3D%22120.3%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
	end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def farmer?
		current_user and current_user.farmer?	
	end

	def consumer?
		current_user and current_user.consumer?
	end

	def current_farmer
		Farmer.find_by_user_id(current_user.id) 
	end

	def current_consumer
		Consumer.find_by_user_id(current_user.id)
	end
end

app/views/shopping_carts/_form.html.erb
<%= form_with(model: shopping_cart, local: true) do |form| %>
  <% if shopping_cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shopping_cart.errors.count, "error") %> prohibited this shopping_cart from being saved:</h2>

      <ul>
        <% shopping_cart.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :consumer_id %>
    <%= form.text_field :consumer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shopping_carts/edit.html.erb
<h1>Editing Shopping Cart</h1>

<%= render 'form', shopping_cart: @shopping_cart %>

<%= link_to 'Show', @shopping_cart %> |
<%= link_to 'Back', shopping_carts_path %>

app/views/shopping_carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shopping Carts</h1>

<table>
  <thead>
    <tr>
      <th>Consumer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shopping_carts.each do |shopping_cart| %>
      <tr>
        <td><%= shopping_cart.consumer_id %></td>
        <td><%= link_to 'Show', shopping_cart %></td>
        <td><%= link_to 'Edit', edit_shopping_cart_path(shopping_cart) %></td>
        <td><%= link_to 'Destroy', shopping_cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shopping Cart', new_shopping_cart_path %>

app/views/shopping_carts/new.html.erb
<h1>New Shopping Cart</h1>

<%= render 'form', shopping_cart: @shopping_cart %>

<%= link_to 'Back', shopping_carts_path %>

app/views/shopping_carts/show.html.erb
<div class="container-fluid pb-10">
	<h1>Items in cart (<%= @shopping_cart.amound_in_cart %>)</h1>

	<% @line_items.each do |item| %>
		<div class="row mb-2">
			<div class="col-md-8 mb-3">
				<div class="card">
					<div class="card-body">
						<% @produce = Produce.find_by_id(item.produce_id) %>
						<div class="d-sm-flex justify-content-between">
							<div class="media d-block d-sm-flex text-center text-sm-left"> <a class="cart-item-thumb mx-auto mr-sm-4" href="#">
								<img src="<%= set_image(@produce) %>" alt="Product" style="width: 140px; height: 140px;"></a>
								<div class="media-body pt-3">
									<h3 class="product-card-title font-weight-semibold border-0 pb-0"><%= @produce.name %></h3>
									<p class="text-muted"><%= @produce.description %></p>
								</div>
							</div>
							<div class="pt-2 pt-sm-0 pl-sm-3 mx-auto mx-sm-0 text-center text-sm-left" style="max-width: 10rem;">
								<p>Quantity</p>
								<p>
									<% if item.quantity != 1 %>
									<%= link_to "-", decrease_quan_line_item_path(item), :method => :patch %>
									<% end %>
									<%= item.quantity %> 
									<%= link_to "+", increase_quan_line_item_path(item), :method => :patch %>		
								</p>	

				 		      <%= link_to "Remove", item, method: :delete, data: { confirm: 'Are you sure?' } %>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="col-md-4">
				<div class="card">
					<div class="card-body">
						<%= simple_form_for(Order.new) do |f| %>
							<%= f.input :note, 
													:label => "Note to seller",
													:input_html => { placeholder: "Give the seller small details about your order eg. please bag in plastic" },
													:hint => "this can be blank" %>
							<%= f.input :line_items_id,
													:as => :hidden,
													:input_html => { value: item.id } %>
							<%= f.input :consumer_id,
													:as => :hidden,
													:input_html => { value: current_user.id } %>
				     <%= f.submit "Place Order", class: "btn btn-primary" %> 
						<% end %>
					</div>
				</div>
			</div>
		</div>
	<% end %>

	<h3 class="mt-10">What Other Users Bought</h3>
	<div class="row mt-4">
		<% @recommendations.each do |recommendation| %>
			<% @produce = Produce.find_by_id(recommendation.produce_id) %>
			<div class="col-md-3">
				<div class="card">
					<div class="card-body">
						<div class="row">
							<div class="media d-block col-md-4"> 
								<a class="cart-item-thumb mx-auto mr-sm-4" href="#">
								<img src="<%= set_image(@produce) %>" alt="Product" style="width: 50px; height: 50px;"></a>
							</div>

							<div class="media-body col-md-4">
								<h5 class="product-card-title font-weight-semibold border-0 pb-0"><%= @produce.name %></h5>
							</div>

		          <div class="col-md-4">
		            <a href="#" data-toggle="modal" data-target=".cart-modal-center_<%= @produce.id %>" class="btn btn-primary btn-sm">Add to cart</a>

		            <div class="modal fade cart-modal-center_<%= @produce.id %>" role="dialog" style="display: none;" aria-hidden="true">
		              <div class="modal-dialog modal-dialog-centered">
			              <div class="modal-content">
			                <div class="modal-body">
			                  <%= simple_form_for(LineItem.new) do |f| %>
			                    <%= f.input :quantity,
			                                :input_html => { :min => 0 } %>
			                    <%= f.input :produce_id, 
			                                :as => :hidden,
			                                :input_html => { :value => @produce.id } %>
			                    <%= f.input :shopping_cart_id, 
			                                :as => :hidden,
			                                :input_html => { :value => ShoppingCart.user_cart(current_user).id } %>
			                    <%= f.submit "Add", class: "btn btn-primary" %> 
			                  <% end %>
			                </div>
			              </div><!-- /.modal-content -->
		              </div><!-- /.modal-dialog -->
		            </div> <!--/.modal-->
		          </div>
						</div>
					</div>
				</div>
			</div>	
		<% end %>
	</div>
</div>