config/routes.rb
Rails.application.routes.draw do
  resources :shopping_carts
  resources :reviews
  resources :consumers
  resources :farmers
	resources :produces
  resources :after_signup
  resources :users, only: [:edit, :update]
  devise_for :users, controllers: { 
  	registrations: 'registrations', 
  	confirmations: 'confirmations'
  }

  resources :line_items do 
    member do 
      patch 'increase_quan'
      patch 'decrease_quan'
    end
  end

  resources :orders do 
    member do
      patch "accept"
      patch "mark_as_complete"
      patch "cancel"
    end
  end

  get 'dashboard/index'
  get 'home/landing'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consumer.rb
class Consumer < ApplicationRecord
  belongs_to :user
	has_many :reviews
  has_one :shoppingcart

  def self.find_by_current_user(current_user_id)
  	self.find_by_user_id(current_user_id)
  end
end

app/models/farm.rb
class Farm < ApplicationRecord
  belongs_to :user
  has_many :produce

	mount_uploader :image, ImageUploader
	
	validates :name, presence: true, uniqueness: true
	validates :description, presence: true
	validates :address_line_1, presence: true
	validates :address_line_2, presence: true
end

app/models/farmer.rb
class Farmer < ApplicationRecord
  belongs_to :user
  has_many :produces
  has_many :reviews

  validates :farm_name, presence: true, uniqueness: true

  def has_consumer_review(id)
    reviews.where(consumer_id: id).present?
  end

  def review
  	reviews.present? ? "#{reviews.average(:rating).ceil} Stars" : "0 Stars"
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :shopping_cart
  belongs_to :order, optional: true
  
  validates :quantity, numericality: { greater_than_or_equal_to: 1 }
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :line_items
	enum status: [:pending, :accepted, :fulfilled, :cancelled]

	def change_status(status)
		update_attributes(status: status)
	end

	def assign_badge_class
		if pending?
			"badge-warning text-white"
		elsif accepted?
			"badge-primary"
		elsif fulfilled?
			"badge-success"
		else
			"badge-danger"
		end	
	end
end

app/models/produce.rb
class Produce < ApplicationRecord
  belongs_to :farmer

	mount_uploaders :images, ImageUploader

  validates :name, presence: true
  validates :description, presence: true

  def seller
  	Farmer.find_by_id(farmer_id)
  end

  def available_to_string
    available? ? "Yes" : "No"  
  end

  def available_badge_class
    available? ? "badge-success" : "badge-danger"  
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :consumer
	belongs_to :farmer, optional: true

	validates :rating, presence: true
	validates :comment, presence: true
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
	has_many :line_items, dependent: :destroy
  belongs_to :consumer

  def self.user_cart(user)
  	self.find_by_consumer_id(Consumer.find_by_user_id(user.id))
  end

  def amound_in_cart
  	line_items.where(order_id: nil).count
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :farmers
	has_many :consumers
  enum state: [:active, :deactivated]

  # validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :address_line_1, presence: true
  # validates :city, presence: true
  # validates :parish, presence: true
  # validates :phone_number, length: { is: 7 }, numericality: { only_integer: true }

  accepts_nested_attributes_for :farmers

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, 
         :timeoutable, :timeout_in => 20.minutes

	mount_uploader :avatar, ImageUploader

 	def consumer?
 		account_type == "consumer"
 	end

 	def farmer?
 		account_type == "farmer"
 	end

end

app/helpers/consumers_helper.rb
module ConsumersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper

end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/produces_helper.rb
module ProducesHelper

	def set_image(produce)
		produce.images.present? ? produce.images.first.url : "data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22348%22%20height%3D%22225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20348%20225%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1761819ef79%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A17pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1761819ef79%22%3E%3Crect%20width%3D%22348%22%20height%3D%22225%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22116.2265625%22%20y%3D%22120.3%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
	end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def farmer?
		current_user and current_user.farmer?	
	end

	def consumer?
		current_user and current_user.consumer?
	end

	def current_farmer
		Farmer.find_by_user_id(current_user.id) 
	end

	def current_consumer
		Consumer.find_by_user_id(current_user.id)
	end
end

app/views/shared/_topnav.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
  <h5 class="my-0 mr-md-auto font-weight-normal">
    <%= link_to root_path, class: "text-dark font-weight-bold navbar-brand" do  %>
      <%= image_tag("logo.svg", style: "width: 10%; height: auto;") %>
      For Farmer
    <% end %>
</h5>
  <nav class="my-2 my-md-0 mr-md-3">
      <% if consumer? %>
        <%= link_to shopping_cart_path(current_user), class: "p-2 text-dark" do  %>
          My Cart (<%= ShoppingCart.user_cart(current_user).amound_in_cart %>)
        <% end %>
      <% end %>
      <% if current_user %>

        <%= link_to 'My Account', edit_user_path(current_user), class: "p-2 text-dark" %>
        <%= link_to 'My Orders', orders_path, class: "p-2 text-dark" %>
       
        <% if farmer? %>
          <%= link_to 'My Farm', produces_path %>
        <% end %>
      </nav>
      <%= link_to 'Sign out', destroy_user_session_path, :method => :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path(), class: "btn btn-primary ml-2" %>
      <%= link_to "User Sign up", new_user_registration_path(type: 'consumer'), class: "btn btn-outline-primary" %>
      <%= link_to "Farmer Sign up", new_user_registration_path(type: 'farmer'), class: "btn btn-outline-primary"  %>
    <% end %>
</div>