config/routes.rb
Rails.application.routes.draw do
  resources :shopping_carts
  resources :reviews
  resources :consumers
  resources :farmers
	resources :produces
  resources :after_signup
  resources :users, only: [:edit, :update]
  devise_for :users, controllers: { 
  	registrations: 'registrations', 
  	confirmations: 'confirmations'
  }

  resources :line_items do 
    member do 
      patch 'increase_quan'
      patch 'decrease_quan'
    end
  end

  resources :orders do 
    member do
      patch "accept"
      patch "mark_as_complete"
      patch "cancel"
    end
  end

  get 'dashboard/index'
  get 'home/landing'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consumer.rb
class Consumer < ApplicationRecord
  belongs_to :user
	has_many :reviews
  has_one :shoppingcart

  def self.find_by_current_user(current_user_id)
  	self.find_by_user_id(current_user_id)
  end
end

app/models/farm.rb
class Farm < ApplicationRecord
  belongs_to :user
  has_many :produce

	mount_uploader :image, ImageUploader
	
	validates :name, presence: true, uniqueness: true
	validates :description, presence: true
	validates :address_line_1, presence: true
	validates :address_line_2, presence: true
end

app/models/farmer.rb
class Farmer < ApplicationRecord
  belongs_to :user
  has_many :produces
  has_many :reviews

  validates :farm_name, presence: true, uniqueness: true

  def has_consumer_review(id)
    reviews.where(consumer_id: id).present?
  end

  def review
  	reviews.present? ? "#{reviews.average(:rating).ceil} Stars" : "0 Stars"
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :shopping_cart
  belongs_to :order, optional: true
  
  validates :quantity, numericality: { greater_than_or_equal_to: 1 }
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :line_items
	enum status: [:pending, :accepted, :fulfilled, :cancelled]

	def change_status(status)
		update_attributes(status: status)
	end

	def assign_badge_class
		if pending?
			"badge-warning text-white"
		elsif accepted?
			"badge-primary"
		elsif fulfilled?
			"badge-success"
		else
			"badge-danger"
		end	
	end
end

app/models/produce.rb
class Produce < ApplicationRecord
  belongs_to :farmer

	mount_uploaders :images, ImageUploader

  validates :name, presence: true
  validates :description, presence: true

  def seller
  	Farmer.find_by_id(farmer_id)
  end

  def available_to_string
    available? ? "Yes" : "No"  
  end

  def available_badge_class
    available? ? "badge-success" : "badge-danger"  
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :consumer
	belongs_to :farmer, optional: true

	validates :rating, presence: true
	validates :comment, presence: true
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
	has_many :line_items, dependent: :destroy
  belongs_to :consumer

  def self.user_cart(user)
  	self.find_by_consumer_id(Consumer.find_by_user_id(user.id))
  end

  def amound_in_cart
  	line_items.where(order_id: nil).count
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :farmers
	has_many :consumers
  enum state: [:active, :deactivated]

  # validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :address_line_1, presence: true
  # validates :city, presence: true
  # validates :parish, presence: true
  # validates :phone_number, length: { is: 7 }, numericality: { only_integer: true }

  accepts_nested_attributes_for :farmers

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, 
         :timeoutable, :timeout_in => 20.minutes

	mount_uploader :avatar, ImageUploader

 	def consumer?
 		account_type == "consumer"
 	end

 	def farmer?
 		account_type == "farmer"
 	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if !current_user
  		redirect_to new_user_session
  	end

  	@produces = Produce.where(available: true)
  	@produces = Produce.where("name ILIKE ?", "%#{params[:search][:name]}%") if params[:search].present?
  end

  def landing
  end
end

app/controllers/produces_controller.rb
class ProducesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_produce, only: [:show, :edit, :update, :destroy]

  # GET /produces
  # GET /produces.json
  def index
    @produces = Farmer.find_by_user_id(current_user.id).produces
  end

  # GET /produces/1
  # GET /produces/1.json
  def show
  end

  # GET /produces/new
  def new
    @produce = Produce.new
  end

  # GET /produces/1/edit
  def edit
  end

  # POST /produces
  # POST /produces.json
  def create
    @produce = Produce.new(produce_params)

    respond_to do |format|
      if @produce.save
        format.html { redirect_to produces_path, notice: 'Produce was successfully created.' }
        format.json { render :show, status: :created, location: @produce }
      else
        format.html { render :new }
        format.json { render json: @produce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produces/1
  # PATCH/PUT /produces/1.json
  def update
    respond_to do |format|
      if @produce.update(produce_params)
        format.html { redirect_to produces_path, notice: 'Produce was successfully updated.' }
        format.json { render :show, status: :ok, location: @produce }
      else
        format.html { render :edit }
        format.json { render json: @produce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produces/1
  # DELETE /produces/1.json
  def destroy
    @produce.destroy
    respond_to do |format|
      format.html { redirect_to produces_url, notice: 'Produce was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produce
      @produce = Produce.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produce_params
      params.require(:produce).permit(:name, :description, :available, :farmer_id, :images => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def toastr_flash
	  flash.each_with_object([]) do |(type, message), flash_messages|
	    type = 'success' if type == 'notice'
	    type = 'error' if type == 'alert'
	    text = "<script>toastr.#{type}('#{message}', '', { closeButton: true, progressBar: true })</script>"
	    flash_messages << text.html_safe if message
	  end.join("\n").html_safe
	end
end

app/helpers/consumers_helper.rb
module ConsumersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper

end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/produces_helper.rb
module ProducesHelper

	def set_image(produce)
		produce.images.present? ? produce.images.first.url : "data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22348%22%20height%3D%22225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20348%20225%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1761819ef79%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A17pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1761819ef79%22%3E%3Crect%20width%3D%22348%22%20height%3D%22225%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22116.2265625%22%20y%3D%22120.3%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
	end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def farmer?
		current_user and current_user.farmer?	
	end

	def consumer?
		current_user and current_user.consumer?
	end

	def current_farmer
		Farmer.find_by_user_id(current_user.id) 
	end

	def current_consumer
		Consumer.find_by_user_id(current_user.id)
	end
end

app/views/produces/_form.html.erb
<%= simple_form_for(@produce) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, placeholder: "name of farm produce" %>

    <%= f.input :description, placeholder: "Eg. Best lettuce in town." %>

    <div class="mb-3">
      <%= f.file_field :images, :multiple => true %>
    </div>

    <%= f.input :available %>

    <%= f.input :farmer_id,
                :as => :hidden, 
                :input_html => { :value => current_farmer.id } %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary mb-3" %>
  </div>
<% end %>

app/views/produces/edit.html.erb
<h1>Editing Produce</h1>

<%= render 'form', produce: @produce %>

<%= link_to 'Show', @produce %> |
<%= link_to 'Back', produces_path %>

app/views/produces/index.html.erb
<section class="container">
  <h2 class="mb-2">Produces</h2>

  <%= link_to 'New Produce', new_produce_path, class: "btn btn-primary mb-3" %>

  <div class="card">
    <div class="card-body">
      <table class="table project-table table-centered table-nowrap">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Available</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>

        <tbody class="">
          <% @produces.each do |produce| %>
            <tr>
              <td><%= produce.name %></td>
              <td><span class="badge <%= produce.available_badge_class %>"><%= produce.available_to_string %></span></td>
              <td><%= link_to 'Show', produce %> | <%= link_to 'Edit', edit_produce_path(produce) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/produces/new.html.erb
<div class="container">
  <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">New Produce</h1>

  <div class="card">
  	<div class="card-body">
			<%= render 'form', produce: @produce %>
			<%= link_to 'Back', produces_path %>
  	</div>
  </div>

</div>

app/views/produces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @produce.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @produce.description %>
</p>

<p>
  <strong>Images:</strong>
  <%= @produce.images %>
</p>

<p>
  <strong>Available:</strong>
  <%= @produce.available %>
</p>

<p>
  <strong>Farm:</strong>
  <%= @produce.farm_id %>
</p>

<%= link_to 'Edit', edit_produce_path(@produce) %> |
<%= link_to 'Back', produces_path %>